package database;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import database.TableRow;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table TABLE_ROW.
*/
public class TableRowDao extends AbstractDao<TableRow, Long> {

    public static final String TABLENAME = "TABLE_ROW";

    /**
     * Properties of entity TableRow.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Value = new Property(1, String.class, "value", false, "VALUE");
        public final static Property InOrder = new Property(2, Integer.class, "inOrder", false, "IN_ORDER");
        public final static Property TableId = new Property(3, long.class, "tableId", false, "TABLE_ID");
    };

    private DaoSession daoSession;

    private Query<TableRow> tableTemplate_TableRowListQuery;

    public TableRowDao(DaoConfig config) {
        super(config);
    }
    
    public TableRowDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'TABLE_ROW' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'VALUE' TEXT," + // 1: value
                "'IN_ORDER' INTEGER," + // 2: inOrder
                "'TABLE_ID' INTEGER NOT NULL );"); // 3: tableId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'TABLE_ROW'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, TableRow entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String value = entity.getValue();
        if (value != null) {
            stmt.bindString(2, value);
        }
 
        Integer inOrder = entity.getInOrder();
        if (inOrder != null) {
            stmt.bindLong(3, inOrder);
        }
        stmt.bindLong(4, entity.getTableId());
    }

    @Override
    protected void attachEntity(TableRow entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public TableRow readEntity(Cursor cursor, int offset) {
        TableRow entity = new TableRow( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // value
            cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2), // inOrder
            cursor.getLong(offset + 3) // tableId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, TableRow entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setValue(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setInOrder(cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2));
        entity.setTableId(cursor.getLong(offset + 3));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(TableRow entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(TableRow entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "tableRowList" to-many relationship of TableTemplate. */
    public List<TableRow> _queryTableTemplate_TableRowList(long tableId) {
        synchronized (this) {
            if (tableTemplate_TableRowListQuery == null) {
                QueryBuilder<TableRow> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.TableId.eq(null));
                tableTemplate_TableRowListQuery = queryBuilder.build();
            }
        }
        Query<TableRow> query = tableTemplate_TableRowListQuery.forCurrentThread();
        query.setParameter(0, tableId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getTableTemplateDao().getAllColumns());
            builder.append(" FROM TABLE_ROW T");
            builder.append(" LEFT JOIN TABLE_TEMPLATE T0 ON T.'TABLE_ID'=T0.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected TableRow loadCurrentDeep(Cursor cursor, boolean lock) {
        TableRow entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        TableTemplate tableTemplate = loadCurrentOther(daoSession.getTableTemplateDao(), cursor, offset);
         if(tableTemplate != null) {
            entity.setTableTemplate(tableTemplate);
        }

        return entity;    
    }

    public TableRow loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<TableRow> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<TableRow> list = new ArrayList<TableRow>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<TableRow> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<TableRow> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
