package database;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import database.TableFieldFilling;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table TABLE_FIELD_FILLING.
*/
public class TableFieldFillingDao extends AbstractDao<TableFieldFilling, Long> {

    public static final String TABLENAME = "TABLE_FIELD_FILLING";

    /**
     * Properties of entity TableFieldFilling.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Content = new Property(1, String.class, "content", false, "CONTENT");
        public final static Property TableFieldId = new Property(2, long.class, "tableFieldId", false, "TABLE_FIELD_ID");
        public final static Property ChildTableId = new Property(3, long.class, "childTableId", false, "CHILD_TABLE_ID");
    };

    private DaoSession daoSession;

    private Query<TableFieldFilling> tableField_TableFieldFillingListQuery;
    private Query<TableFieldFilling> childTable_TableFieldFillingQuery;

    public TableFieldFillingDao(DaoConfig config) {
        super(config);
    }
    
    public TableFieldFillingDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'TABLE_FIELD_FILLING' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'CONTENT' TEXT," + // 1: content
                "'TABLE_FIELD_ID' INTEGER NOT NULL ," + // 2: tableFieldId
                "'CHILD_TABLE_ID' INTEGER NOT NULL );"); // 3: childTableId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'TABLE_FIELD_FILLING'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, TableFieldFilling entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String content = entity.getContent();
        if (content != null) {
            stmt.bindString(2, content);
        }
        stmt.bindLong(3, entity.getTableFieldId());
        stmt.bindLong(4, entity.getChildTableId());
    }

    @Override
    protected void attachEntity(TableFieldFilling entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public TableFieldFilling readEntity(Cursor cursor, int offset) {
        TableFieldFilling entity = new TableFieldFilling( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // content
            cursor.getLong(offset + 2), // tableFieldId
            cursor.getLong(offset + 3) // childTableId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, TableFieldFilling entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setContent(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setTableFieldId(cursor.getLong(offset + 2));
        entity.setChildTableId(cursor.getLong(offset + 3));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(TableFieldFilling entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(TableFieldFilling entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "tableFieldFillingList" to-many relationship of TableField. */
    public List<TableFieldFilling> _queryTableField_TableFieldFillingList(long tableFieldId) {
        synchronized (this) {
            if (tableField_TableFieldFillingListQuery == null) {
                QueryBuilder<TableFieldFilling> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.TableFieldId.eq(null));
                tableField_TableFieldFillingListQuery = queryBuilder.build();
            }
        }
        Query<TableFieldFilling> query = tableField_TableFieldFillingListQuery.forCurrentThread();
        query.setParameter(0, tableFieldId);
        return query.list();
    }

    /** Internal query to resolve the "tableFieldFilling" to-many relationship of ChildTable. */
    public List<TableFieldFilling> _queryChildTable_TableFieldFilling(long childTableId) {
        synchronized (this) {
            if (childTable_TableFieldFillingQuery == null) {
                QueryBuilder<TableFieldFilling> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.ChildTableId.eq(null));
                childTable_TableFieldFillingQuery = queryBuilder.build();
            }
        }
        Query<TableFieldFilling> query = childTable_TableFieldFillingQuery.forCurrentThread();
        query.setParameter(0, childTableId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getTableFieldDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getChildTableDao().getAllColumns());
            builder.append(" FROM TABLE_FIELD_FILLING T");
            builder.append(" LEFT JOIN TABLE_FIELD T0 ON T.'TABLE_FIELD_ID'=T0.'_id'");
            builder.append(" LEFT JOIN CHILD_TABLE T1 ON T.'CHILD_TABLE_ID'=T1.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected TableFieldFilling loadCurrentDeep(Cursor cursor, boolean lock) {
        TableFieldFilling entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        TableField tableField = loadCurrentOther(daoSession.getTableFieldDao(), cursor, offset);
         if(tableField != null) {
            entity.setTableField(tableField);
        }
        offset += daoSession.getTableFieldDao().getAllColumns().length;

        ChildTable childTable = loadCurrentOther(daoSession.getChildTableDao(), cursor, offset);
         if(childTable != null) {
            entity.setChildTable(childTable);
        }

        return entity;    
    }

    public TableFieldFilling loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<TableFieldFilling> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<TableFieldFilling> list = new ArrayList<TableFieldFilling>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<TableFieldFilling> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<TableFieldFilling> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
