DELETE FROM Therapist;
DELETE FROM Kid;
DELETE FROM ResolvePeriod;
DELETE FROM Program;
DELETE FROM Tab;
DELETE FROM KidTab;
DELETE FROM TabRow;
DELETE FROM TabField;
DELETE FROM TabFieldResolve;
INSERT INTO Therapist (id, login, name, surname, password) VALUES(0,'Alicja.Kowalska','Alicja','Kowalska','abc123');
INSERT INTO Therapist (id, login, name, surname, password) VALUES(1,'Elzbieta.Nowak','Elzbieta','Nowak','abc123');
INSERT INTO Therapist (id, login, name, surname, password) VALUES(2,'Milena.Zielinska','Milena','Zielinska','abc123');
INSERT INTO Therapist (id, login, name, surname, password) VALUES(3,'Katarzyna.Glowacka','Katarzyna','Glowacka','abc123');
INSERT INTO Therapist (id, login, name, surname, password) VALUES(4,'Julita.Wisniewska','Julita','Wisniewska','abc123');
INSERT INTO Therapist (id, login, name, surname, password) VALUES(5,'Iwona.Dratwa','Iwona','Dratwa','abc123');
INSERT INTO Kid (id, code) VALUES(0,'IP627');
INSERT INTO ResolvePeriod (id, begin_date, end_date, kid_id) VALUES(0,'2016-03-03','2016-03-09',0);
INSERT INTO ResolvePeriod (id, begin_date, end_date, kid_id) VALUES(1,'2016-03-10','2016-03-16',0);
INSERT INTO ResolvePeriod (id, begin_date, end_date, kid_id) VALUES(2,'2016-03-17','2016-03-23',0);
INSERT INTO ResolvePeriod (id, begin_date, end_date, kid_id) VALUES(3,'2016-03-24','2016-03-30',0);
INSERT INTO ResolvePeriod (id, begin_date, end_date, kid_id) VALUES(4,'2016-03-31','2016-04-06',0);
INSERT INTO ResolvePeriod (id, begin_date, end_date, kid_id) VALUES(5,'2016-04-07','2016-04-13',0);
INSERT INTO ResolvePeriod (id, begin_date, end_date, kid_id) VALUES(6,'2016-04-14','2016-04-20',0);
INSERT INTO Program (id, symbol, name, description, kid_id) VALUES(0,'U1316','Nazwa programu U1316','Opis programu U1316',0);
